# Copyright 2023 (C) Peter McGoron
# This file is a part of Upsilon, a free and open source software project.
# For license terms, refer to the files in `doc/copying` in the Upsilon
# source distribution.

all:
	echo "dummy"

#make_spi:
#	cd spi && make codegen


#make_bram:
#	cd bram && make codegen
#clean:
#	cd bram && make clean
