# Copyright 2023 (C) Peter McGoron
# This file is a part of Upsilon, a free and open source software project.
# For license terms, refer to the files in `doc/copying` in the Upsilon
# source distribution.

#all: make_bram

dummy:
	@echo empty

#make_bram:
#	cd bram && make codegen
#clean:
#	cd bram && make clean
